import "./globals.css";
import { Inter } from "next/font/google";
import { app } from "@/auth/firebase.auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wedding Line",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
